# Generated by Django 2.0.6 on 2021-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20210709_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libros',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autors'),
        ),
    ]
